name: hcheck-cron
on:
  schedule:
  - cron:  '9,24,39,54 * * * *'
  workflow_dispatch:

jobs:
  hcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v2

      - name: Run main Python script
        env:
          HCHECK_API_URL: ${{ secrets.HCHECK_API_URL }}
          HCHECK_LOGIN_URL: ${{ secrets.HCHECK_LOGIN_URL }}
          HCHECK_LOGIN_USER: ${{ secrets.HCHECK_LOGIN_USER }}
          HCHECK_LOGIN_PASS: ${{ secrets.HCHECK_LOGIN_PASS }}
          WORKLOAD_LABELS_B64: ${{ secrets.WORKLOAD_LABELS_B64 }}
          NOTIFY_URL: ${{ secrets.NOTIFY_URL }}
        run: python3 ./main.py

