name: hcheck-cron
on:
    schedule:
        - cron:  '*/2 * * * *'

jobs:
    hcheck:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v2

            - name: Run main Python script
              env:
                TESTVAR: vMWMceGU3v
              run: python3 ./main.py

